apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sidekiq
    component: sidekiq-connector
  name: sidekiq-connector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sidekiq
        component: sidekiq-connector
    spec:
      containers:
      - name: kafka
        image: kirankumarcelestial/sidekiq-connector:1.0.7
        imagePullPolicy: Always
        env:
          - name: gateway_url
            value: "a56d6c9b55f2011eaae4402584498c9a-350195318.us-west-2.elb.amazonaws.com:8080"
          - name: queues
            value: "faas-request"
          - name: redis_host
            value: "a2d26e6055fee11eabe2a0e49a1a7f5b-1221548443.us-west-2.elb.amazonaws.com:6379"
          - name: print_response
            value: "true"
